Capitulo 2
semanticmx/html5-042022 pull request #4
Opened 2022-06-23 20:19 UTC by EliMejia

envió el Capitulo dos para revisión de existir correcciones las realizo a la brevedad posible gracias

2022-06-24 03:09 UTC, semanticmx requested changes
la cuestión de HTML es que aunque algo falle el navegador hará su mayor esfuerzo para hacer que el contenido se despliegue lo mejor posible.

Esto hace difícil encontrar fallos en el código ya que serán difíciles de detectar visualmente.

Por eso hay que tener especial cuidado en que el código se pueda leer bien, especialmente en HTML identificar que etiquetas están anidadas, donde se abren y donde se cierran.

2022-06-24 03:09 UTC, semanticmx commented on Capitulo2/APIHistorial.html
> +  return !!(window.history && history.pushState);
hay que cuidar la identación del código.

de preferencia usar 2 o 4 espacios por cada nivel de identación

2022-06-24 03:09 UTC, semanticmx commented on Capitulo2/AlmaceLocal.html
> +  <title>Canvas Ejemplo</title>
también aplica para los tags anidados, hay que identarlos también

2022-06-30 22:44 UTC, EliMejia reviewed
Entendido checo los comentarios para aplicar los cambios

2022-06-30 22:45 UTC, closed without merging